import type { ScanResult } from '../lib/scanner'

function bar(count:number, total:number, color:string){
  const w = total? (count/total)*100 : 0
  return <div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full" style={{ width:`${w}%`, background: color }} /></div>
}

export default function ReportDashboard({ result }: { result: ScanResult }){
  const counts = result.findings.reduce((a:any,f)=>{ a[f.severity]++; return a },{critical:0,high:0,medium:0,low:0,info:0} as any)
  const total = result.findings.length || 1
  const byRule = Object.entries(result.findings.reduce((a:any,f)=>{ a[f.rule]=(a[f.rule]||0)+1; return a },{} as Record<string,number>)).sort((a:any,b:any)=> b[1]-a[1]).slice(0,5)
  const manifest = result.manifest || {}

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>vsixgate report — ${result.publisher}.${result.name}</title><style>body{font-family:system-ui;padding:32px;max-width:800px;margin:auto;color:#0F172A}h1{font-size:22px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #E2E8F0;padding:8px;text-align:left;font-size:13px}th{background:#F8FAFC}</style></head><body><h1>${result.publisher}.${result.name}@${result.version} — ${result.status} ${result.score}/100</h1><p>Generated by vsixgate v0.1.0 — ${new Date().toISOString()}</p><table><tr><th>Severity</th><th>Count</th></tr>${['critical','high','medium','low','info'].map(k=>`<tr><td>${k}</td><td>${counts[k]||0}</td></tr>`).join('')}<\/table><h2>Findings</h2><table><tr><th>Rule</th><th>Severity</th><th>Message</th><\/tr>${result.findings.map(f=>`<tr><td>${f.rule}<\/td><td>${f.severity}<\/td><td>${f.message}<\/td><\/tr>`).join('')}<\/table><\/body><\/html>`

  const openHtml = ()=>{
    const w = window.open('','_blank')
    if(!w) return
    w.document.write(html); w.document.close()
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2 justify-between items-center">
        <div className="text-sm font-semibold">HTML dashboard — view & print in browser</div>
        <div className="flex gap-2">
          <button onClick={openHtml} className="rounded-full bg-slate-900 text-white px-4 py-1.5 text-xs font-bold">Open HTML</button>
          <button onClick={()=> { const blob=new Blob([html],{type:'text/html'}); const u=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=u; a.download=`vsixgate-${result.publisher}.${result.name}-${result.version}.html`; a.click(); URL.revokeObjectURL(u)}} className="rounded-full bg-white border px-4 py-1.5 text-xs font-bold">Download HTML</button>
          <button onClick={()=> window.print()} className="rounded-full bg-amber-100 border border-amber-200 text-amber-800 px-4 py-1.5 text-xs font-bold">Print</button>
        </div>
      </div>

      <div className="grid md:grid-cols-3 gap-3">
        <div className="rounded-2xl border bg-white p-4">
          <div className="text-xs tracking-widest text-ink-400 font-bold">SCORE</div>
          <div className="mt-2 text-3xl font-bold">{result.score}<span className="text-sm font-normal text-ink-400">/100</span></div>
          <div className={`mt-1 inline-flex text-xs px-2 py-1 rounded-full font-bold ${result.status==='BLOCK'?'bg-red-600 text-white':result.status==='WARN'?'bg-amber-500 text-white':'bg-emerald-600 text-white'}`}>{result.status}</div>
          <div className="mt-3 space-y-1.5 text-xs">
            {(['critical','high','medium','low','info'] as const).map(k=> counts[k]>0 && <div key={k} className="flex justify-between"><span className="capitalize">{k}</span><span className="font-mono">{counts[k]}</span></div>)}
          </div>
        </div>
        <div className="rounded-2xl border bg-white p-4 md:col-span-2">
          <div className="text-xs tracking-widest text-ink-400 font-bold">SEVERITY DISTRIBUTION</div>
          <div className="mt-3 space-y-2">
            {(['critical','high','medium','low'] as const).map(k=>(
              <div key={k} className="flex items-center gap-2 text-xs">
                <span className="w-16 capitalize">{k}</span>
                {bar(counts[k], total, k==='critical'?'#DC2626':k==='high'?'#F59E0B':k==='medium'?'#EAB308':'#38BDF8')}
                <span className="w-8 text-right font-mono">{counts[k]||0}</span>
              </div>
            ))}
          </div>
          <div className="mt-4 text-xs text-ink-500">Top rules: {byRule.map(([r,c])=> `${r} (${c})`).join(' • ') || '—'}</div>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-3">
        <div className="rounded-2xl border bg-white p-4">
          <div className="text-xs tracking-widest text-ink-400 font-bold">MANIFEST</div>
          <div className="mt-2 text-sm space-y-1 font-mono">
            <div>publisher: <b>{manifest.publisher || result.publisher}</b></div>
            <div>name: <b>{manifest.name || result.name}</b></div>
            <div>version: <b>{manifest.version || result.version}</b></div>
            <div>engines: <b>{manifest.engines?.vscode || '—'}</b></div>
            <div>activationEvents: <b>{(manifest.activationEvents||[]).join(', ') || '—'}</b></div>
          </div>
        </div>
        <div className="rounded-2xl border bg-white p-4">
          <div className="text-xs tracking-widest text-ink-400 font-bold">WHAT TO DO</div>
          <ul className="mt-2 text-sm list-disc pl-5 space-y-1 text-ink-700">
            {result.status==='BLOCK' ? <><li>Block publish — fix critical/high first</li><li>Add allowlist for shell args, remove eval</li><li>Verify images are not PE/ELF</li></> : result.status==='WARN' ? <><li>Review medium/high, add mitigations</li><li>Switch http → https</li><li>Commit lockfile</li></> : <><li>Keep SARIF in CI</li><li>Enable --strict</li></>}
            <li className="text-xs text-ink-400">Exit code {result.status==='BLOCK'?2:result.status==='WARN'?1:0} — wire to GitHub Actions</li>
          </ul>
        </div>
      </div>

      <div className="rounded-2xl border bg-white overflow-hidden">
        <div className="px-4 py-3 border-b bg-slate-50 text-sm font-semibold">Findings table</div>
        <div className="overflow-auto max-h-[320px]">
          <table className="w-full text-sm">
            <thead className="bg-slate-50 text-xs text-ink-400 sticky top-0"><tr><th className="text-left p-2">Severity</th><th className="text-left p-2">Rule</th><th className="text-left p-2">Message</th></tr></thead>
            <tbody className="divide-y">
              {result.findings.map((f,i)=>(
                <tr key={i} className="hover:bg-slate-50"><td className="p-2"><span className={`text-[11px] px-1.5 py-0.5 rounded-full font-bold ${f.severity==='critical'?'bg-red-600 text-white':f.severity==='high'?'bg-amber-500 text-white':f.severity==='medium'?'bg-amber-100 text-amber-800 border':'bg-slate-100 border'}`}>{f.severity}</span></td><td className="p-2 font-mono text-xs">{f.rule}</td><td className="p-2 text-xs">{f.message}</td></tr>
              ))}
              {result.findings.length===0 && <tr><td colSpan={3} className="p-6 text-center text-sm text-ink-500">Clean — no findings</td></tr>}
            </tbody>
          </table>
        </div>
      </div>
      <div className="text-xs text-ink-400 text-center">This HTML dashboard is generated client-side. No data leaves your browser — printable, shareable, auditable.</div>
    </div>
  )
}
